FROM node:lts
WORKDIR /usr/src/app

COPY ./backend/package*.json ./backend/yarn.lock ./
ENV PUPPETEER_SKIP_DOWNLOAD=ture
RUN yarn && yarn cache clean --all

COPY ./backend/prisma/schema.prisma ./prisma/schema.prisma
RUN npx prisma generate

COPY ./backend .

RUN npm run build 

CMD ["yarn migrate:deploy && yarn start"]
